export const DELETE_FORM = "DELETE_FORM";
export const RECIVE_FORMS = "RECIVE_FORMS";
export const GET_APPROVE_LIST_COUNT = "GET_APPROVE_LIST_COUNT";
export const CLEAR_APPROVE_COUNT = "CLEAR_APPROVE_COUNT";







