export const RECEIVED_LOGIN_DATA = "RECEIVED_LOGIN_DATA";
export const RECEIVED_ACCESS_DATA = "RECEIVED_ACCESS_DATA";
export const RECEIVED_SUBMIT_ACCESS = "RECEIVED_SUBMIT_ACCESS";
export const GET_FORM_DATA = "GET_FORM_DATA";