export const SET_DATA = "SET_DATA";
export const LOAD = "LOAD";
export const CREATE = "CREATE";
export const DELETE = "DELETE";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const SAVE = "SAVE";
export const SET_ITEM_ATTR = "SET_ITEM_ATTR";
export const SET_FORMCHILDITEM_ATTR = "SET_FORMCHILDITEM_ATTR";
export const SET_FORMCHILDITEM_VALUES = "SET_FORMCHILDITEM_VALUES";
export const SET_FORM_NAME = "SET_FORM_NAME";

export const SET_ITEM_VALUES = "SET_ITEM_VALUES";
export const INIT_FORM_DOM = "INIT_FORM_DOM";
export const INIT_FORM_BEFORE = "Init_FORM_BEFORE"

export const RECALC_LAYOUT = "RECALC_LAYOUT";
export const SET_DRAG_STATE = "SET_DRAG_STATE";
export const GET_ALL_FORMS = "GET_ALL_FORMS";
export const SET_ACTIVE_INDEX = "SET_ACTIVE_INDEX";


export const ADD_VERIFICATION = "ADD_VERIFICATION";
export const DELETE_VERIFICATION = "DELETE_VERIFICATION";
export const EDIT_VERIFICATION = "EDIT_VERIFICATION";
export const SET_VERIFICATION = "SET_VERIFICATION";
export const SET_VERIFICATION_MSG = "SET_VERIFICATION_MSG";

export const SAVE_FORM_CHANGE = "SAVE_FORM_CHANGE";

export const SET_ACTIVEINNERINDEX = "SET_ACTIVEINNERINDEX";

export const SET_NEWFORMLAYOUT = "SET_NEWFORMLAYOUT";
export const SET_FORMLAYOUTLIST = "SET_FORMLAYOUTLIST";

export const SET_ERROR_COMPONENT_INDEX = "SET_ERROR_COMPONENT_INDEX";